#!/usr/bin/env ruby

keys_and_values = [[1, 'one'], [2, 'two'], [3, 'san']]

h = Hash[keys_and_values]

puts "Array of key-value pairs"
puts keys_and_values.inspect

puts "Hash obtained form that array"
puts h.inspect

