#!/usr/bin/env ruby

# # #
#
#

env = {"ADDRESSEE" =>"Castor"}
puts "Running say_hello with custom environment #{env.inspect}:"
cmd1 = IO.popen(env, "./say_hello", "r")
puts cmd1.readlines

puts "\n"
env = {"ADDRESSEE" =>"Pollux"}
puts "Running say_hello with custom environment #{env.inspect}:"
cmd1 = IO.popen(env, "./say_hello", "r")
puts cmd1.readlines
