#!/usr/bin/env ruby

months = {
	   "Jan" => "January",
	   "Feb" => "February",
	   "Mar" => "March",
	   "Apr" => "April",
	   "May" => "Might", # :-)
	   "Jun" => "June",
	   "Jul" => "July",
	   "Aug" => "August",
	   "Sep" => "September",
	   "Oct" => "October",
	   "Nov" => "November",
	   "Dec" => "December"
}

vals = months.values_at "Dec", "May", "can", "Feb", "aug"

puts vals.inspect

