#!/usr/bin/env ruby

# # #
# USAGE: load_queries data/words.txt [other_file(s)]
#

Encoding::default_external = 'Windows-1252'

ignorecase = true

queries = File.readlines(ARGV.shift).select do |line|
  line.chomp!
  unless line.empty?
    line.upcase!  if ignorecase
  end
end

puts "A few words from the beginning and end of the array"
puts queries.values_at(0..2, -3..-1).inspect

puts "Now searching..."
while line = gets
  line.chomp!

  words = line.split

  if ignorecase
    words.map {|w| w.upcase!}
  end

  words.each_with_index do |word, idx|
    if queries.include?(word)
      puts "#{word}\t#{idx}\t#{line}"
    end
  end
end

