#!/usr/bin/env ruby

numbers = [1, 3,4,5,  7, 9,  11,12,13,14]
grp_numbers = [[1], [3,4,5], [7], [9], [11,12,13,14]]

def group_numbers nums
  grp = [nums[0]]
  groups = [grp]

  1.upto(nums.length-1) do |idx|
    if nums[idx] == nums[idx-1]+1
      grp << nums[idx]
    else
      grp = [nums[idx]]
      groups << grp
    end
  end

  groups
end

puts "Initial: #{numbers.inspect}"

grouped = group_numbers(numbers)
puts "Grouped: #{grouped.inspect}"

puts grp_numbers == grouped
