#!/usr/bin/env ruby

numbers = [1, 3,4,5,  7, 9,  11,12,13,14]
grp_numbers = [[1], [3,4,5], [7], [9], [11,12,13,14]]

def group_numbers nums
  grp = []
  groups = [grp]

  # TODO: add your code here

  groups
end

puts "Initial: #{numbers.inspect}"

grouped = group_numbers(numbers)
puts "Grouped: #{grouped.inspect}"

puts grp_numbers == grouped
