#!/usr/bin/env ruby

def fibo_nth(n)
  -1
end

gold_fibos = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765]

gold_fibos.each_with_index do |gold, idx|
  puts fibo_nth(idx) == gold
end
