#!/usr/bin/env ruby

def fibo_nth(n)
  0
end

gold = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765]

puts fibo_nth(2)  == gold[2]
puts fibo_nth(3)  == gold[3]
puts fibo_nth(4)  == gold[4]
puts fibo_nth(5)  == gold[5]
puts fibo_nth(20) == gold[20]
