#!/usr/bin/env ruby

parsing = \
   ["w_complete_sentence",
       ["w_cl_fin",
		   ["w_ng_d",   "Wessen_PISG_0"],
		   ["w_cl_fin", "gedenkt_VLPI3S_1",
		      ["w_ng_io_n", 
			    ["w_ng_n", "man_PSSN_2"],
				["w_ng_io", 
                   [ "w_ap_ng", "am_APPD_3",
                                ["w_ncmsd", "25._ZO_4", "August_NCMSD_5" ]]]]]],
	"?_?_6"]


def indent n
  " " * n * 3
end

def show_parsing prs, level=0
  tree = ""
  prs.each_with_index do |node, pos|
    if node.instance_of? Array
      tree << show_parsing(node, level+1)
    else
      if pos == 0
        # node name
        tree << "\n" + indent(level) + node
      else
        # node value, always indented one level deeper than the node name
        tree << "\n" + indent(level+1) + node
      end
    end
  end
  tree
end

puts show_parsing parsing
