#!/usr/bin/env ruby

# ex: Wessen gedenkt man am 25. August ?
parsing1 = \
   ["w_complete_sentence",
       ["w_cl_fin",
		   ["w_ng_d",
              ["Wessen_PISG_0"],
		    "w_cl_fin",
              ["gedenkt_VLPI3S_1",
		       "w_ng_io_n", 
			      ["w_ng_n",
                     ["man_PSSN_2"],
				   "w_ng_io", 
                     ["w_ap_ng",
                        ["am_APPD_3",
                         "w_ncmsd",
                           ["25._ZO_4", "August_NCMSD_5" ]]]]]],
	   "?_?_6"]]

# ex: I love apples and pears that my grandparents grow in their garden
parsing2 = \
   ["w__Sentence",
      ["I_PP1A",
       "w__VB_XX",
          ["love_VB",
           "w_NNS_HP_CC",
             ["apples_NNS",
              "and_CC",
              "pears_NNS"]]],
    "that_CS",
    "w__Sentence",
       ["w_NNS",
           ["my_PP$",
            "grandparents_NNS"],
        "w__VB_XX",
           ["grow_VB",
            "w__IN_N",
               ["in_IN",
                "w_NN",
                   ["their_PP$",
                    "garden_NN"]]]]]

def parse_bracketed_ps tokens
  []
end

def indent n
  " " * n * 3
end

def show_parsing nodes, level=-1
  return nodes.to_s
end

[parsing1, parsing2].each do |parsing|
  puts show_parsing parsing
end
