#!/usr/bin/env ruby

def digital_root num
  if num < 10
    num
  else
    digital_root(num % 10 + digital_root(num/10))
  end
end

puts digital_root(1)    == 1
puts digital_root(999)  == 9
puts digital_root(9999) == 9
puts digital_root(1729) == 1
puts digital_root(1111111111) == 1

