#!/usr/bin/env ruby

str = 'X_NN provides_VBZ a_AT flexible_JJ and_CC powerful_JJ Y_NN for_IN Z_NN'

md = str.match(/((\w+)_JJ[RT]?) (\w+)_CC ((\w+)_JJ[RT]?)/)
puts md.inspect

puts "\nUsing MatchData#[]"

0.upto(md.length-1) do |idx|
  puts "parenthesis ##{idx}: #{md[idx]}"
end

puts "\nUsing MatchData#to_a"

md.to_a.each_with_index do |m, idx|
  puts "parenthesis ##{idx}: #{m}"
end

puts "\nUsing MatchData#captures"
#puts md.captures.inspect

md.captures.each_with_index do |m, idx|
  puts "parenthesis ##{idx}: #{m}"
end
