#!/usr/bin/env ruby

str = "Hello, World"

puts "in an AND expression"
if (md1 = str.match(/[[:punct:]]/)) && (md2 = str.match(/[[:upper:]]/))
  puts "1st match: #{md1.inspect}"
  puts "2nd match: #{md2.inspect}"
end

puts "\nin an OR expression"

if (md10 = str.match(/[[:punct:]]/)) || (md20 = str.match(/[[:upper:]]/))
  puts "1st match: #{md10.inspect}"
  puts "2nd match: #{md20.inspect}"
end
