#!/usr/bin/env ruby

# /x option -- multiline regexps

re = /([01]?[0-9]|2[0-4])        # hours
      \ ?:\ ?([0-5][0-9])        # minutes
      (?:\ ?:\ ?([0-5][0-9]))?   # seconds
      $/x

["03 : 15 : 25", "4:10", "25 : 10"].each do |str|
  md = str.match(re)
  puts md.captures.inspect
end
