#!/usr/bin/env ruby

# # #
# USAGE: ./intersect noun_negative.srcsmd [eng_negative_effect_translated_ch]
#
# use diff -b to compare the output with the original file, ignoring space chars

require 'json'

Encoding::default_external = 'utf-8'

def suitable? line
  line !~ /^\s*#/ && line =~ /\S/
end

# load spec dict into an array
known_words = File.read(ARGV.shift)
  .split(/\n/)
  .map { |word| word.chomp.strip }
  .select { |word| suitable? word }

#puts known_words.inspect

# read the file with english chinese correspondences and from the chinese part
# remove words that are in known_words
while line = gets
  line.chomp!

  if suitable?(line)
    en_word, ch_data = line.split(/ *\t */)
    ch_words = JSON.parse(ch_data) # same as: eval(ch_data) !!! TODO: explain

    # delete words that are also in known_words
    ch_words = ch_words - known_words # !!! TODO: explain set operations, show Venn diagrams

    puts en_word + "\t" + ch_words.inspect
  end
end

