#!/usr/bin/env ruby

# # #
#
#

require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "
  Find words/phrases from words_to_search in given text_files
USAGE: #{File.basename($0)} [OPTIONS] words_to_search text_file(s)
OPTIONS:
"
  opts.on('-h', '--help', 'display this message and exit') do
    puts opts
    exit 0
  end

  options[:ignorecase] = false
  opts.on('-i', '--ignore-case', 'search case insensitively') do
    options[:ignorecase] = true
  end

  options[:output_totals] = false
  opts.on('-t', '--output-totals', 'output the number of finds of each query word (to stderr)') do
    options[:output_totals] = true
  end

  opts.separator " "

end.parse!

######################################################################

Encoding::default_external = 'Windows-1252'

lines = File.readlines(ARGV.shift)

lines.map!{ |line| 
  line.chomp
}.select!{ |line| 
  ! line.empty?
}

if options[:ignorecase]
  lines.map!{ |line| line.upcase }
end

queries = Hash[lines.map {|l| [l, 0]}]
# OR
#queries = {}
#lines.each {|l| queries[l] = 0 }

# selftests
#puts queries.include?("Although") == true
#puts queries.include?("although") == false
#puts queries.include?("Extensible Markup Language") == true

######################################################################

while line = gets
  line.chomp!

  words = line.split

  words.each_with_index do |word, pos|
    if options[:ignorecase]
      word = word.upcase
    end
    if queries.include? word
      puts "%s\t%s\t%s" % [word, pos, line]
      queries[word] += 1
    end
  end
end

if options[:output_totals]
  queries.each { |query, count|
    $stderr.puts "#{query}\t#{count}"
  }
end

