#SENTENCENUM	1
#SRCFILE	-
But	but	CC
would	would	MD
they	they	PP3AS
do	do	DO
it	it	PP3
?	?	?

#SENTENCENUM	2
#SRCFILE	-
Bill	bill	NP
had	had	HVD
said	said	VBN
he	he	PP3A
would	would	MD
be	be	BE
back	back	RP
home	home	NR
not	not	XNOT
later	later	RBR
than	than	IN
one	one	CD1
o'clock	o'clock	RB
.	.	.

#SENTENCENUM	3
#SRCFILE	-
The	the	ATI
judge	judge	NN
had	had	HVD
decided	decided	VBN
that	that	CS
Bill	bill	NP
and	and	CC
the	the	ATI
young	young	JJ
Indian	indian	NNP
had	had	HVD
accepted	accepted	VBN
the	the	ATI
inevitable	inevitable	JJ
and	and	CC
sensibly	sensibly	RB
decided	decided	VBN
to	to	TO
wait	wait	VB
for	for	IN
the	the	ATI
gale	gale	NN
to	to	TO
blow	blow	VB
itself	itself	PPL
out	out	RP
when	when	WRB
he	he	PP3A
caught	caught	VBD
and	and	CC
held	held	VBD
his	his	PP$
breath	breath	NN
,	,	,
then	then	RB
rose	rose	VBD
hastily	hastily	RB
.	.	.

#SENTENCENUM	4
#SRCFILE	-
Around	around	IN
that	that	DT
rounded	rounded	JJed
rocky	rocky	JJ
promontory	promontory	NN
where	where	WRB
the	the	ATI
white	white	JJ
spray	spray	NN
could	could	MD
be	be	BE
seen	seen	VBN
flying	flying	VBG
across	across	IN
the	the	ATI
distance	distance	NN
of	of	IN
a	a	AT
mile	mile	NN
and	and	CC
a	a	AT
half	half	ABN
,	,	,
came	came	VBD
the	the	ATI
yawl	yawl	NN
under	under	IN
her	her	PP$
full	full	JJ
triangular	triangular	JJ
sail	sail	NN
,	,	,
and	and	CC
to	to	TO
the	the	ATI
judge	judge	NN
's	's	POS
frightened	frightened	JJed
eyes	eyes	NNS
,	,	,
so	so	QL
close	close	RB
to	to	TO
the	the	ATI
rocks	rocks	NNS
that	that	CS
it	it	PP3
would	would	MD
be	be	BE
dashed	dashed	VBN
against	against	IN
them	them	PP3OS
with	with	IN
the	the	ATI
lift	lift	NN
of	of	IN
the	the	ATI
next	next	AP
wave	wave	NN
.	.	.

#SENTENCENUM	7
#SRCFILE	-
What	what	WDT
does	does	DOZ
he	he	PP3A
mean	mean	VB
by	by	IN
trying	trying	VBG
to	to	TO
come	come	VB
home	home	NR
now	now	RN
,	,	,
even_if	even_if	CS
he	he	PP3A
did	did	DOD
promise	promise	VB
?	?	?

#SENTENCENUM	15
#SRCFILE	-
When	when	WRB
the	the	ATI
wind	wind	NN
was	was	BEDZ
on	on	IN
a	a	AT
rampage	rampage	NN
,	,	,
as	as	CS
it	it	PP3
was	was	BEDZ
now	now	RN
,	,	,
it	it	PP3
could	could	MD
kick	kick	VB
up	up	RP
a	a	AT
sea-sized	sea-sized	JJ
commotion	commotion	NN
where	where	WRB
it	it	PP3
had	had	HVD
a	a	AT
straight	straight	JJ
blow	blow	NN
of	of	IN
eight	eight	CD
miles	miles	NNS
down	down	IN
the	the	ATI
lake	lake	NN
.	.	.

#SENTENCENUM	18
#SRCFILE	-
Maybe	maybe	RB
by_and_by	by_and_by	RB
she	she	PP3A
blow	blow	VB
some	some	RB
more	more	RBR
.	.	.
'	'	RQ

#SENTENCENUM	20
#SRCFILE	-
'	'	LQ
I	i	PP1A
did	did	DOD
n't	n't	XNOT
hear	hear	VB
you	you	PP2
.	.	.

#SENTENCENUM	29
#SRCFILE	-
Chapter	chapter	NN
19	19	CD
.	.	.

#SENTENCENUM	57
#SRCFILE	-
A_few	a_few	AP
moments	moments	NNS
later	later	RBR
the	the	ATI
yawl	yawl	NN
was	was	BEDZ
upside	upside	NN
down	down	RP
,	,	,
exposing	exposing	VBG
its	its	PP$
shallow	shallow	JJ
keel	keel	NN
.	.	.

#SENTENCENUM	97
#SRCFILE	-
One	one	CD1
of	of	IN
these	these	DTS
was	was	BEDZ
that	that	CS
an	an	AT
officer	officer	NN
should	should	MD
join	join	VB
a	a	AT
ship	ship	NN
,	,	,
on	on	IN
taking	taking	VBG
up	up	RP
a	a	AT
new	new	JJ
appointment	appointment	NN
,	,	,
at	at	IN
nine	nine	CD
a.m	a.m	RB
precisely	precisely	RB
,	,	,
dressed	dressed	VBN
in	in	IN
the	the	ATI
modern	modern	JJ
equivalent	equivalent	NN
of	of	IN
frock-coat	frock-coat	NN
and	and	CC
sword	sword	NN
.	.	.

#SENTENCENUM	101
#SRCFILE	-
The	the	ATI
lower	lower	JJR
bar	bar	NN
was	was	BEDZ
empty	empty	JJ
,	,	,
save_for	save_for	IN
the	the	ATI
lady	lady	NN
known	known	VBN
by	by	IN
all	all	ABN
habitue*?2s	habitue*?2s	NNS
as	as	IN
'	'	LQ
Seaweed	seaweed	NP
'	'	RQ
,	,	,
and	and	CC
a	a	AT
youngish	youngish	JJ
,	,	,
sharp-eyed	sharp-eyed	JJ
man	man	NN
who	who	WP
was	was	BEDZ
staring	staring	VBG
moodily	moodily	RB
into	into	IN
a	a	AT
gin	gin	NN
and	and	CC
tonic	tonic	NN
.	.	.

#SENTENCENUM	113
#SRCFILE	-
Youngest	youngest	JJT
D.S.C	d.s.c	NPT
in	in	IN
the	the	ATI
war	war	NN
,	,	,
what	what	WDT
?	?	?

#SENTENCENUM	115
#SRCFILE	-
Should	should	MD
have	have	HV
been	been	BEN
a	a	AT
V.C	v.c	NPT
.	.	.

#SENTENCENUM	138
#SRCFILE	-
I	i	PP1A
'm	'm	BEM
a	a	AT
Lieutenant-Commander	lieutenant-commander	NPT
.	.	.

#SENTENCENUM	194
#SRCFILE	-
'	'	LQ
Good-oh	good-oh	UH
!	!	!

#SENTENCENUM	227
#SRCFILE	-
'	'	LQ
Supposing	supposing	VBG
I	i	PP1A
was	was	BEDZ
to	to	TO
tell	tell	VB
you	you	PP2
that	that	CS
we	we	PP1AS
've	've	HV
had	had	HVN
Pericles	pericles	NP
'	'	POS
entire	entire	JJ
snort	snort	NN
equipment	equipment	NN
removed	removed	VBN
and	and	CC
X-rayed	x-rayed	VBN
and	and	CC
that	that	CS
it	it	PP3
was	was	BEDZ
as	as	QL
sound	sound	JJ
as	as	IN
a	a	AT
bell	bell	NN
?	?	?
'	'	RQ
said	said	VBD
John	john	NP
.	.	.

#SENTENCENUM	257
#SRCFILE	-
Acute	acute	JJ
neurasthenia	neurasthenia	NN
,	,	,
said	said	VBD
the	the	ATI
surgeon-rear-admiral	surgeon-rear-admiral	NN
.	.	.

#SENTENCENUM	312
#SRCFILE	-
'	'	LQ
All_right	all_right	RB
,	,	,
sir	sir	NN
.	.	.
'	'	RQ

#SENTENCENUM	343
#SRCFILE	-
The	the	ATI
shiny	shiny	JJ
Merce*?2de*?3s	merce*?2de*?3s	NP
was	was	BEDZ
there	there	RN
,	,	,
its	its	PP$
windows	windows	NNS
shattered	shattered	VBN
as_of	as_of	IN
the	the	ATI
previous	previous	JJ
night	night	NN
.	.	.

#SENTENCENUM	590
#SRCFILE	-
'Light	'light	VB
an'	an'	CC
come	come	VB
on	on	RP
in	in	RP
.	.	.
'	'	RQ

#SENTENCENUM	686
#SRCFILE	-
The	the	ATI
troopers	troopers	NNS
had	had	HVD
been	been	BEN
joshing	joshing	VBG
with	with	IN
a	a	AT
starry-eyed	starry-eyed	JJ
Toma*?2s	toma*?2s	NP
.	.	.

#SENTENCENUM	808
#SRCFILE	-
The	the	ATI
boy	boy	NN
spat	spat	VBD
between	between	IN
his	his	PP$
teeth	teeth	NNS
-	-	DA
just	just	RB
like	like	IN
O'Shay	o'shay	NP
-	-	DA
and	and	CC
pressed	pressed	VBD
his	his	PP$
thumbs	thumbs	NNS
down	down	RP
on	on	IN
the	the	ATI
pistol	pistol	NN
belt	belt	NN
-	-	DA
just	just	RB
like	like	IN
Clanton	clanton	NP
.	.	.

#SENTENCENUM	975
#SRCFILE	-
A	a	AT
P.38	p.38	FO
.	.	.

#SENTENCENUM	1448
#SRCFILE	-
'	'	LQ
D'	d'	DO
you	you	PP2
want	want	VB
me	me	PP1O
to	to	TO
guess	guess	VB
?	?	?
'	'	RQ

#SENTENCENUM	1877
#SRCFILE	-
Or	or	CC
they	they	PP3AS
might	might	MD
shoot	shoot	VB
his	his	PP$
horses	horses	NNS
,	,	,
or	or	CC
even	even	RB
try	try	VB
to	to	TO
bushwhack	bushwhack	VB
him	him	PP3O
,	,	,
but	but	CC
when	when	WRB
it	it	PP3
came	came	VBD
to	to	TO
stand-up-and-fight	stand-up-and-fight	NN
,	,	,
or	or	CC
cut	cut	NN
and	and	CC
run	run	NN
,	,	,
lead	lead	NN
bullets	bullets	NNS
or	or	CC
fast	fast	JJ
horses	horses	NNS
,	,	,
he	he	PP3A
knew	knew	VBD
which	which	WDT
way	way	NN
they	they	PP3AS
'd	'd	MD
go	go	VB
.	.	.

#SENTENCENUM	1940
#SRCFILE	-
'	'	LQ
Ma'm	ma'm	NN
,	,	,
my	my	PP$
father	father	NN
built	built	VBD
this	this	DT
road	road	NN
almost	almost	RB
thirty	thirty	CD
years	years	NNS
ago	ago	RB
.	.	.

#SENTENCENUM	2034
#SRCFILE	-
When	when	WRB
he	he	PP3A
'd	'd	HVD
finally	finally	RB
become	become	VBN
reconciled	reconciled	VBN
to	to	TO
not	not	XNOT
dying	dying	VBG
heroically	heroically	RB
at	at	IN
my	my	PP$
hands	hands	NNS
,	,	,
the	the	ATI
little	little	JJ
man	man	NN
told	told	VBD
me	me	PP1O
he	he	PP3A
was	was	BEDZ
Sara	sara	NP
Lundgren	lundgren	NP
's	's	POS
fiance	fiance	NN
,	,	,
Raoul	raoul	NP
Carlsson	carlsson	NP
,	,	,
of	of	IN
the	the	ATI
house	house	NN
of	of	IN
Carlsson	carlsson	NP
and	and	CC
LeClaire	leclaire	NP
,	,	,
women	women	NNS
's	's	POS
clothing	clothing	NN
,	,	,
Stockholm	stockholm	NP
,	,	,
Paris	paris	NP
,	,	,
London	london	NP
,	,	,
Rome	rome	NP
.	.	.

#SENTENCENUM	2119
#SRCFILE	-
Rostat	rostat	NP
bro"d	bro"d	NP
,	,	,
they	they	PP3AS
call	call	VB
it	it	PP3
,	,	,
'	'	RQ
she	she	PP3A
said	said	VBD
.	.	.

#SENTENCENUM	2125
#SRCFILE	-
When	when	WRB
the	the	ATI
company	company	NN
car	car	NN
arrived	arrived	VBD
,	,	,
right	right	RB
on	on	IN
schedule	schedule	NN
,	,	,
it	it	PP3
turned	turned	VBD
out	out	RP
to	to	TO
be	be	BE
a	a	AT
long	long	JJ
,	,	,
black	black	JJ
,	,	,
dignified-looking	dignified-looking	JJ
old	old	JJ
Chrysler	chrysler	NP
limousine	limousine	NN
complete	complete	JJ
with	with	IN
one	one	CD1
middle-aged	middle-aged	JJ
gent	gent	NN
in	in	IN
a	a	AT
chauffeur	chauffeur	NN
's	's	POS
cap	cap	NN
to	to	TO
drive	drive	VB
it	it	PP3
,	,	,
and	and	CC
one	one	CD1
young	young	JJ
guy	guy	NN
named	named	VBN
Lindstro"m	lindstro"m	NP
to	to	TO
answer	answer	VB
our	our	PP$
questions	questions	NNS
and	and	CC
keep	keep	VB
us	us	PP1OS
out	out	RP
of	of	IN
trouble	trouble	NN
.	.	.

#SENTENCENUM	2149
#SRCFILE	-
He	he	PP3A
objected	objected	VBD
to	to	TO
her	her	PP$
going	going	VBG
to	to	TO
the	the	ATI
juke-box	juke-box	NN
cafe*?2	cafe*?2	NN
where	where	WRB
her	her	PP$
friends	friends	NNS
met	met	VBD
regularly	regularly	RB
.	.	.

#SENTENCENUM	2236
#SRCFILE	-
She	she	PP3A
saw	saw	VBD
the	the	ATI
light	light	NN
in	in	IN
his	his	PP$
study	study	NN
and	and	CC
guessed	guessed	VBD
that	that	CS
he	he	PP3A
was	was	BEDZ
working	working	VBG
on	on	IN
a	a	AT
new	new	JJ
TV	tv	NN
play	play	NN
.	.	.

#SENTENCENUM	3227
#SRCFILE	-
Hide-and-seek	hide-and-seek	NN
with	with	IN
a	a	AT
killer	killer	NN
.	.	.

#SENTENCENUM	3611
#SRCFILE	-
'	'	LQ
No'	no'	XNOT
me	me	PP1O
.	.	.

#SENTENCENUM	3641
#SRCFILE	-
'	'	LQ
H'm	h'm	UH
.	.	.

#SENTENCENUM	4875
#SRCFILE	-
If	if	CS
they	they	PP3AS
get	get	VB
in	in	RP
before	before	IN
eight-thirty	eight-thirty	CD
,	,	,
even_though	even_though	CS
they	they	PP3AS
're	're	BER
standing	standing	VBG
on	on	IN
one_another's	one_another's	PPLS
toes	toes	NNS
,	,	,
I	i	PP1A
've	've	HV
got	got	VBN
to	to	TO
see	see	VB
'em	'em	PP3OS
.	.	.

#SENTENCENUM	4886
#SRCFILE	-
D.j	d.j	NP
and	and	CC
all	all	ABN
.	.	.

#SENTENCENUM	5012
#SRCFILE	-
As	as	CS
shown	shown	VBN
in	in	IN
Figure	figure	NN
2A	2a	CD
,	,	,
in_order_to	in_order_to	TO
remove	remove	VB
cartridge	cartridge	NN
12	12	CD
from	from	IN
reproduction	reproduction	NN
machine	machine	NN
10	10	CD
,	,	,
access	access	NN
door	door	NN
40	40	CD
,	,	,
which	which	WP
is	is	BEZ
on	on	IN
the	the	ATI
right	right	JJ
end	end	NN
of	of	IN
machine	machine	NN
10	10	CD
as	as	CS
one	one	PN
faces	faces	VBZ
the	the	ATI
front	front	NN
of	of	IN
the	the	ATI
machine	machine	NN
,	,	,
is	is	BEZ
lowered	lowered	VBN
and	and	CC
through	through	IN
conventional	conventional	JJ
linkage	linkage	NN
76	76	CD
rotates	rotates	VBZ
pulley	pulley	NN
73	73	CD
away_from	away_from	IN
timing	timing	JJing
belt	belt	NN
71	71	CD
to	to	TO
an	an	AT
inactive	inactive	JJ
position	position	NN
while	while	CS
simultaneously	simultaneously	RB
rotating	rotating	VBG
gear	gear	NN
80	80	CD
to	to	TO
enhance	enhance	VB
removal	removal	NN
of	of	IN
a	a	AT
developer	developer	NN
cartridge	cartridge	NN
.	.	.

#SENTENCENUM	5033
#SRCFILE	-
Ketal	ketal	NP
rearrangement	rearrangement	NN
:	:	:
(RS)-2-(1-bromoethyl)	(rs)-2-(1-bromoethyl)	NN
-	-	DA
-	-	DA
2-(6-methoxy-2-naphthyl)-5	2-(6-methoxy-2-naphthyl)-5	NN
,	,	,
5	5	CD
-	-	DA
dimethyl-1	dimethyl-1	NN
,	,	,
3-dioxane	3-dioxane	NN
and	and	CC
sodium	sodium	NN
acetate	acetate	NN
were	were	BED
dissolved	dissolved	VBN
in	in	IN
an	an	AT
aqueous	aqueous	JJ
solution	solution	NN
of	of	IN
acetic	acetic	JJ
acid	acid	NN
.	.	.

#SENTENCENUM	5034
#SRCFILE	-
The	the	ATI
mixture	mixture	NN
was	was	BEDZ
heated	heated	VBN
to	to	TO
110°C	110c	NP
,	,	,
and	and	CC
maintained	maintained	VBN
at	at	IN
that	that	DT
temperature	temperature	NN
for	for	IN
16	16	CD
hours	hours	NNS
.	.	.

#SENTENCENUM	5040
#SRCFILE	-
3	3	CD
,	,	,
7	7	CD
and	and	CC
11	11	CD
are	are	BER
examples	examples	NNS
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
with	with	IN
the	the	ATI
treatment	treatment	NN
in	in	IN
the	the	ATI
heat	heat	NN
cycle	cycle	NN
according_to	according_to	IN
the	the	ATI
present	present	JJ
process	process	NN
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
7	7	CD
.	.	.

#SENTENCENUM	5042
#SRCFILE	-
Examples	examples	NNS
of	of	IN
curing	curing	JJing
acceleration	acceleration	NN
catalyst	catalyst	NN
:	:	:
Examples	examples	NNS
of	of	IN
such	such	ABL
polymer	polymer	NN
include	include	VB
:	:	:
plant	plant	NN
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
guar	guar	NP
gum	gum	NN
,	,	,
locust	locust	NN
bean	bean	NN
gum	gum	NN
,	,	,
gum	gum	NN
arabic	arabic	JNP
,	,	,
tragacanth	tragacanth	NN
,	,	,
carrageenah	carrageenah	NP
,	,	,
pectin	pectin	NN
,	,	,
mannan	mannan	NP
,	,	,
and	and	CC
starch	starch	NN
;	;	;
microorganism	microorganism	NN
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
xanthane	xanthane	NN
gum	gum	NN
,	,	,
dextrin	dextrin	NN
,	,	,
succinoglucan	succinoglucan	NP
,	,	,
and	and	CC
curdran	curdran	NP
;	;	;
animal	animal	JJ
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
gelatin	gelatin	NN
,	,	,
casein	casein	NN
,	,	,
albumin	albumin	NN
,	,	,
and	and	CC
collagen	collagen	NN
;	;	;
cellulose	cellulose	NN
polymers	polymers	NNS
such_as	such_as	IN
methyl	methyl	NN
cellulose	cellulose	NN
,	,	,
ethyl	ethyl	NN
cellulose	cellulose	NN
,	,	,
and	and	CC
hydroxyethyl	hydroxyethyl	NN
cellulose	cellulose	NN
;	;	;
starch	starch	NN
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
soluble	soluble	JJ
starch	starch	NN
,	,	,
carboxymethyl	carboxymethyl	NN
starch	starch	NN
,	,	,
and	and	CC
methyl	methyl	NN
starch	starch	NN
;	;	;
alginic	alginic	JJ
acid	acid	NN
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
propylene	propylene	NN
glycol	glycol	NN
alginate	alginate	NN
,	,	,
and	and	CC
alginic	alginic	JJ
acid	acid	NN
salts	salts	NNS
;	;	;
other	other	DT
semisynthetic	semisynthetic	JJ
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
derivatives	derivatives	NNS
of	of	IN
polysaccharides	polysaccharides	NNS
;	;	;
vinyl	vinyl	NN
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
polyvinyl	polyvinyl	NN
alcohol	alcohol	NN
,	,	,
polyvinylpyrolidone	polyvinylpyrolidone	NN
,	,	,
polyvinyl	polyvinyl	NN
methyl	methyl	NN
ether	ether	NN
,	,	,
carboxyvinyl	carboxyvinyl	NN
polymer	polymer	NN
,	,	,
and	and	CC
sodium	sodium	NN
polyacrylate	polyacrylate	NN
;	;	;
and	and	CC
other	other	DT
synthetic	synthetic	JJ
polymers	polymers	NNS
,	,	,
such_as	such_as	IN
polyethylene	polyethylene	NN
glycol	glycol	NN
,	,	,
ethylene	ethylene	NN
oxide	oxide	NN
-	-	DA
propylene	propylene	NN
oxide	oxide	NN
block	block	NN
copolymer	copolymer	NN
;	;	;
alkyd	alkyd	NN
resin	resin	NN
,	,	,
phenolic	phenolic	JJ
resin	resin	NN
,	,	,
epoxy	epoxy	JJ
resin	resin	NN
,	,	,
aminoalkyd	aminoalkyd	NP
resin	resin	NN
,	,	,
polyester	polyester	NN
resin	resin	NN
,	,	,
polyurethane	polyurethane	NN
resin	resin	NN
,	,	,
acrylic	acrylic	JJ
resin	resin	NN
,	,	,
polyamide	polyamide	NN
resin	resin	NN
,	,	,
polyamide-imide	polyamide-imide	NN
resin	resin	NN
,	,	,
polyester-imide	polyester-imide	NN
resin	resin	NN
,	,	,
and	and	CC
silicone	silicone	NN
resin	resin	NN
;	;	;
etc.	etc.	RB

#SENTENCENUM	5046
#SRCFILE	-
Examples	examples	NNS
of	of	IN
the	the	ATI
group	group	NN
represented	represented	VBN
by	by	IN
Ar	ar	NP
¹		FO
,	,	,
Ar	ar	NP
²		CD
,	,	,
Ar	ar	NP
³		NP
,	,	,
Ar#sup4#	ar#sup4#	NP
,	,	,
Ar#sup5#	ar#sup5#	NP
,	,	,
Ar#sup6#	ar#sup6#	NP
and	and	CC
Ar#sup7#	ar#sup7#	NP
include	include	VB
a	a	AT
C#sub6#	c#sub6#	NP
Þ		NP
£		NP
½		CD
arylene	arylene	NN
groups	groups	NNS
such_as	such_as	IN
phenylene	phenylene	NN
,	,	,
naphthalene	naphthalene	NN
,	,	,
antolylene	antolylene	NN
,	,	,
biphenylene	biphenylene	NN
and	and	CC
terphenylene	terphenylene	NN
,	,	,
divalent	divalent	JJ
groups	groups	NNS
derived	derived	VBN
from	from	IN
a	a	AT
condensed	condensed	JJed
polycyclic	polycyclic	JJ
aromatic	aromatic	JJ
group	group	NN
,	,	,
such_as	such_as	IN
indene	indene	NN
,	,	,
fluorene	fluorene	NN
,	,	,
acenaphthene	acenaphthene	NN
,	,	,
perylene	perylene	NN
,	,	,
fluorenone	fluorenone	NN
,	,	,
anthrone	anthrone	NN
,	,	,
anthraquinone	anthraquinone	NN
,	,	,
benzoanthrone	benzoanthrone	NN
and	and	CC
isocoumarin	isocoumarin	NN
,	,	,
and	and	CC
divalent	divalent	JJ
groups	groups	NNS
derived	derived	VBN
from	from	IN
a	a	AT
heterocyclic	heterocyclic	JJ
aromatic	aromatic	JJ
group	group	NN
,	,	,
such_as	such_as	IN
pyridine	pyridine	NN
,	,	,
quinoline	quinoline	NN
,	,	,
oxazole	oxazole	NN
,	,	,
thiazole	thiazole	NN
,	,	,
oxadiazole	oxadiazole	NN
,	,	,
benzooxazole	benzooxazole	NN
,	,	,
benzoimidazole	benzoimidazole	NN
,	,	,
benzothiazole	benzothiazole	NN
,	,	,
benzotriazole	benzotriazole	NN
,	,	,
dibenzofurane	dibenzofurane	NN
,	,	,
carbazole	carbazole	NN
,	,	,
and	and	CC
xanthene	xanthene	NN
.	.	.

#SENTENCENUM	5049
#SRCFILE	-
Examples	examples	NNS
of	of	IN
the	the	ATI
polyhydric	polyhydric	JJ
alcohol-type	alcohol-type	JJ
solvent	solvent	NN
to	to	TO
be	be	BE
used	used	VBN
as	as	IN
a	a	AT
liquid	liquid	JJ
dispersion	dispersion	NN
medium	medium	NN
used	used	VBN
in	in	IN
the	the	ATI
recording	recording	JJing
material	material	NN
according_to	according_to	IN
the	the	ATI
present	present	JJ
invention	invention	NN
may	may	MD
include	include	VB
:	:	:
ethylene	ethylene	NN
glycol	glycol	NN
,	,	,
propylene	propylene	NN
glycol	glycol	NN
,	,	,
diethylene	diethylene	NN
glycol	glycol	NN
,	,	,
triethylene	triethylene	NN
glycol	glycol	NN
,	,	,
tetraethylene	tetraethylene	NN
glycol	glycol	NN
,	,	,
polyethylene	polyethylene	NN
glycol	glycol	NN
,	,	,
ethylene	ethylene	NN
glycol	glycol	NN
monomethyl	monomethyl	NN
ether	ether	NN
,	,	,
ethylene	ethylene	NN
glycol	glycol	NN
monoethyl	monoethyl	NN
ether	ether	NN
,	,	,
ethylene	ethylene	NN
glycol	glycol	NN
monobutyl	monobutyl	NN
ether	ether	NN
,	,	,
methyl	methyl	NN
carbitol	carbitol	NN
,	,	,
ethyl	ethyl	NN
carbitol	carbitol	NN
,	,	,
butyl	butyl	NN
carbitol	carbitol	NN
,	,	,
ethyl	ethyl	NN
carbitol	carbitol	NN
acetate	acetate	NN
,	,	,
diethyl	diethyl	NN
carbitol	carbitol	NN
,	,	,
triethylene	triethylene	NN
glycol	glycol	NN
monomethyl	monomethyl	NN
ether	ether	NN
,	,	,
triethylene	triethylene	NN
glycol	glycol	NN
monoethyl	monoethyl	NN
ether	ether	NN
,	,	,
propylene	propylene	NN
glycol	glycol	NN
monomethyl	monomethyl	NN
ether	ether	NN
,	,	,
dipropylene	dipropylene	NN
glycol	glycol	NN
,	,	,
hexylene	hexylene	NN
glycol	glycol	NN
,	,	,
glycerin	glycerin	NP
,	,	,
1,2,6-hexane-thiol	1,2,6-hexane-thiol	NN
,	,	,
diacetin	diacetin	NP
,	,	,
etc.	etc.	RB

#SENTENCENUM	5053
#SRCFILE	-
Regarding	regarding	IN
the	the	ATI
following	following	JJing
explanations	explanations	NNS
,	,	,
it	it	PP3
is	is	BEZ
to	to	TO
be	be	BE
noted	noted	VBN
that	that	CS
the	the	ATI
unit	unit	NN
1	1	CD
G=10	g=10	NP
min	min	NNU
;	;	;
4	4	CD
;	;	;
T	t	NP
and	and	CC
that	that	CS
the	the	ATI
unit	unit	NN
1	1	CD
Oe=0.0796	oe=0.0796	NP
k	k	NP
·		.
A/m	a/m	NNU
and	and	CC
that	that	CS
the	the	ATI
unit	unit	NN
1	1	CD
MGOe=7.96	mgoe=7.96	NP
K	k	NP
J/m	j/m	NNU
³		NP
.	.	.

#SENTENCENUM	5054
#SRCFILE	-
FIG.	fig.	NN
10	10	CD
is	is	BEZ
a	a	AT
photomicrograph	photomicrograph	NN
at	at	IN
4,470X	4,470x	NP
magnifification	magnifification	NN
of	of	IN
a	a	AT
section	section	NN
of	of	IN
a	a	AT
microporous	microporous	JJ
polyacrilonitrile	polyacrilonitrile	NN
bead	bead	NN
of	of	IN
this	this	DT
invention	invention	NN
illustrating	illustrating	VBG
a	a	AT
uniform	uniform	JJ
pore	pore	NN
interior	interior	JJ
structure	structure	NN
.	.	.

#SENTENCENUM	5059
#SRCFILE	-
The	the	ATI
functions	functions	NNS
of	of	IN
the	the	ATI
various	various	JJ
control	control	JJ
elements	elements	NNS
are	are	BER
described	described	VBN
in	in	IN
my	my	PP$
U.	u.	NP
S	s	NP
Patent	patent	JJ
No.	no.	NN
4,706,481	4,706,481	CD
,	,	,
issued	issued	VBN
November	november	NR
17	17	CD
,	,	,
1987	1987	CD
,	,	,
and	and	CC
my	my	PP$
pending	pending	JJing
U.S.	u.s.	NPL
patent	patent	JJ
application	application	NN
,	,	,
Serial	serial	JJ
No.	no.	NN
139,678	139,678	CD
,	,	,
filed	filed	VBN
December	december	NR
30	30	CD
,	,	,
1987	1987	CD
.	.	.

#SENTENCENUM	5064
#SRCFILE	-
Controlled	controlled	JJed
formation	formation	NN
of	of	IN
masking	masking	JJing
layer	layer	NN
42	42	CD
may	may	MD
alternatively	alternatively	RB
take	take	VB
the	the	ATI
form	form	NN
of	of	IN
deliberate	deliberate	JJ
exposure	exposure	NN
to	to	TO
reactant	reactant	NN
material	material	NN
,	,	,
e.g.	e.g.	NN
air	air	NN
,	,	,
oxygen	oxygen	NN
,	,	,
sulphur	sulphur	NN
or	or	CC
other	other	DT
material	material	NN
yielding	yielding	VBG
a	a	AT
mask	mask	NN
of	of	IN
properties	properties	NNS
appropriate	appropriate	JJ
to	to	TO
contemplated	contemplated	JJed
processing	processing	NN
.	.	.

#SENTENCENUM	5074
#SRCFILE	-
FIGURE	figure	NN
1	1	CD
is	is	BEZ
a	a	AT
block	block	NN
diagram	diagram	NN
of	of	IN
a	a	AT
television	television	NN
receiver	receiver	NN
embodying	embodying	VBG
the	the	ATI
invention	invention	NN
;	;	;
FIGURE	figure	NN
1	1	CD
is	is	BEZ
a	a	AT
graph	graph	NN
in	in	IN
which	which	WP
fatigue	fatigue	NN
crack	crack	JJ
growth	growth	NN
in	in	IN
inches	inches	NNS
per	per	IN
cycle	cycle	NN
is	is	BEZ
plotted	plotted	VBN
on	on	IN
a	a	AT
log	log	NN
scale	scale	NN
against	against	IN
ultimate	ultimate	JJ
tensile	tensile	JJ
strength	strength	NN
in	in	IN
ksi	ksi	NP
.	.	.

#SENTENCENUM	5076
#SRCFILE	-
Graph	graph	NN
3A	3a	NP
shows	shows	VBZ
the	the	ATI
timing	timing	NN
for	for	IN
the	the	ATI
finish	finish	NN
of	of	IN
the	the	ATI
recording/reproducing	recording/reproducing	JJing
operation	operation	NN
by	by	IN
the	the	ATI
first	first	OD
recording/reproducing	recording/reproducing	JJing
system	system	NN
10	10	CD
.	.	.

#SENTENCENUM	5083
#SRCFILE	-
Fig.	fig.	NN
1	1	CD
is	is	BEZ
a	a	AT
perspective	perspective	NN
view	view	NN
of	of	IN
the	the	ATI
apparatus	apparatus	NN
used	used	VBN
in	in	IN
one	one	CD1
stage	stage	NN
of	of	IN
the	the	ATI
method	method	NN
;	;	;
Fig.	fig.	NN
2	2	CD
is	is	BEZ
a	a	AT
cross-section	cross-section	NN
along	along	IN
the	the	ATI
line	line	NN
II-II	ii-ii	NP
of	of	IN
Fig.	fig.	NN
1	1	CD
;	;	;
Fig.	fig.	NN
3	3	CD
is	is	BEZ
a	a	AT
cross-section	cross-section	NN
similar	similar	JJ
to	to	TO
Fig.	fig.	NN
2	2	CD
during	during	IN
a	a	AT
further	further	JJR
stage	stage	NN
of	of	IN
the	the	ATI
method	method	NN
;	;	;
Fig.	fig.	NN
4	4	CD
is	is	BEZ
a	a	AT
perspective	perspective	NN
view	view	NN
of	of	IN
the	the	ATI
semi-finished	semi-finished	JJ
product	product	NN
;	;	;
Fig.	fig.	NN
5	5	CD
is	is	BEZ
a	a	AT
perspective	perspective	NN
view	view	NN
of	of	IN
the	the	ATI
finished	finished	JJed
product	product	NN
.	.	.

#SENTENCENUM	5086
#SRCFILE	-
Fig.	fig.	NN
1	1	CD
is	is	BEZ
a	a	AT
schematic	schematic	JJ
perspective	perspective	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
relation	relation	NN
between	between	IN
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
direction	direction	NN
and	and	CC
the	the	ATI
direction	direction	NN
of	of	IN
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
a	a	AT
polarizing	polarizing	JJing
plate	plate	NN
in	in	IN
a	a	AT
conventional	conventional	JJ
TN-LCD	tn-lcd	NP
;	;	;
Fig.	fig.	NN
2	2	CD
is	is	BEZ
a	a	AT
schematic	schematic	JJ
perspective	perspective	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
relation	relation	NN
between	between	IN
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
direction	direction	NN
and	and	CC
the	the	ATI
direction	direction	NN
of	of	IN
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
a	a	AT
polarizing	polarizing	JJing
plate	plate	NN
in	in	IN
a	a	AT
conventional	conventional	JJ
STN-LCD	stn-lcd	NP
;	;	;
Fig.	fig.	NN
3	3	CD
is	is	BEZ
a	a	AT
schematic	schematic	JJ
perspective	perspective	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
relation	relation	NN
between	between	IN
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
direction	direction	NN
and	and	CC
the	the	ATI
direction	direction	NN
of	of	IN
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
a	a	AT
polarizing	polarizing	JJing
plate	plate	NN
in	in	IN
a	a	AT
conventional	conventional	JJ
OMI-LCD	omi-lcd	NP
;	;	;
Fig.	fig.	NN
4	4	CD
is	is	BEZ
a	a	AT
schematic	schematic	JJ
perspective	perspective	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
relation	relation	NN
between	between	IN
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
direction	direction	NN
and	and	CC
the	the	ATI
direction	direction	NN
of	of	IN
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
a	a	AT
polarizing	polarizing	JJing
plate	plate	NN
in	in	IN
a	a	AT
conventional	conventional	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
5	5	CD
is	is	BEZ
a	a	AT
spectral	spectral	JJ
characteristic	characteristic	NN
chart	chart	NN
illustrating	illustrating	VBG
spectral	spectral	JJ
distributions	distributions	NNS
of	of	IN
transmitting	transmitting	JJing
light	light	NN
in	in	IN
open	open	JJ
and	and	CC
close	close	JJ
states	states	NNS
in	in	IN
the	the	ATI
TN-LCD	tn-lcd	NP
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
1	1	CD
;	;	;
Fig.	fig.	NN
6	6	CD
is	is	BEZ
a	a	AT
spectral	spectral	JJ
characteristic	characteristic	NN
chart	chart	NN
illustrating	illustrating	VBG
spectral	spectral	JJ
distributions	distributions	NNS
of	of	IN
transmitting	transmitting	JJing
light	light	NN
in	in	IN
open	open	JJ
and	and	CC
close	close	JJ
states	states	NNS
in	in	IN
the	the	ATI
STN-LCD	stn-lcd	NP
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
2	2	CD
;	;	;
Fig.	fig.	NN
7	7	CD
is	is	BEZ
a	a	AT
CIE	cie	NP
chromaticity	chromaticity	NN
chart	chart	NN
illustrating	illustrating	VBG
the	the	ATI
hue	hue	NN
of	of	IN
transmitting	transmitting	JJing
light	light	NN
in	in	IN
open	open	JJ
and	and	CC
close	close	JJ
states	states	NNS
in	in	IN
the	the	ATI
TN-LCD	tn-lcd	NP
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
1	1	CD
,	,	,
which	which	WP
is	is	BEZ
attained	attained	VBN
on	on	IN
the	the	ATI
basis	basis	NN
of	of	IN
the	the	ATI
spectral	spectral	JJ
characteristic	characteristic	NN
chart	chart	NN
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
6	6	CD
;	;	;
Fig.	fig.	NN
8	8	CD
is	is	BEZ
a	a	AT
cross-sectional	cross-sectional	JJ
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
structure	structure	NN
of	of	IN
a	a	AT
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
according_to	according_to	IN
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
9A	9a	NP
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
relation	relation	NN
between	between	IN
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
direction	direction	NN
of	of	IN
a	a	AT
substrate	substrate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
the	the	ATI
direction	direction	NN
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
a	a	AT
polarizing	polarizing	JJing
plate	plate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
9B	9b	NP
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
relation	relation	NN
between	between	IN
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
direction	direction	NN
of	of	IN
a	a	AT
substrate	substrate	NN
on	on	IN
the	the	ATI
outgoing	outgoing	JJing
light	light	NN
side	side	NN
and	and	CC
the	the	ATI
direction	direction	NN
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
a	a	AT
polarizing	polarizing	JJing
plate	plate	NN
on	on	IN
the	the	ATI
outgoing	outgoing	JJing
light	light	NN
side	side	NN
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
10	10	CD
is	is	BEZ
a	a	AT
spectral	spectral	JJ
characteristic	characteristic	NN
chart	chart	NN
illustrating	illustrating	VBG
spectral	spectral	JJ
distributions	distributions	NNS
of	of	IN
transmitting	transmitting	JJing
light	light	NN
in	in	IN
open	open	JJ
and	and	CC
close	close	JJ
states	states	NNS
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
11	11	CD
is	is	BEZ
a	a	AT
CIE	cie	NP
chromaticity	chromaticity	NN
chart	chart	NN
illustrating	illustrating	VBG
the	the	ATI
hue	hue	NN
of	of	IN
transmitting	transmitting	JJing
light	light	NN
in	in	IN
open	open	JJ
and	and	CC
close	close	JJ
states	states	NNS
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
,	,	,
which	which	WP
is	is	BEZ
attained	attained	VBN
on	on	IN
the	the	ATI
basis	basis	NN
of	of	IN
the	the	ATI
spectral	spectral	JJ
characteristic	characteristic	NN
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
10	10	CD
;	;	;
Fig.	fig.	NN
12	12	CD
is	is	BEZ
a	a	AT
graph	graph	NN
illustrating	illustrating	VBG
the	the	ATI
direction	direction	NN
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plate	plate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	JJ
side	side	NN
and	and	CC
a	a	AT
change	change	NN
in	in	IN
contrast	contrast	NN
with	with	IN
respect	respect	NN
to	to	TO
the	the	ATI
direction	direction	NN
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axis	axis	NN
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plate	plate	NN
on	on	IN
the	the	ATI
outgoing	outgoing	JJing
light	light	NN
side	side	NN
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
13	13	CD
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
directions	directions	NNS
of	of	IN
the	the	ATI
substrate	substrate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
and	and	CC
the	the	ATI
directions	directions	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axes	axes	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plates	plates	NNS
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
with	with	IN
a	a	AT
twist	twist	NN
angle	angle	NN
#	FO
phis	phis	NP
#	FO
=	=	FO
180	180	CD
°		FO
and	and	CC
n·d	nd	NP
=	=	FO
0	0	CD
6	6	CD
according_to	according_to	IN
another	another	DT
embodiment	embodiment	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
14	14	CD
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
directions	directions	NNS
of	of	IN
the	the	ATI
substrate	substrate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
and	and	CC
the	the	ATI
directions	directions	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axes	axes	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plates	plates	NNS
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
with	with	IN
a	a	AT
twist	twist	NN
angle	angle	NN
#	FO
phis	phis	NP
#	FO
=	=	FO
180	180	CD
°		FO
and	and	CC
n·d	nd	NP
=	=	FO
0.7	0.7	CD
according_to	according_to	IN
a	a	AT
different	different	JJ
embodiment	embodiment	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
15	15	CD
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
directions	directions	NNS
of	of	IN
the	the	ATI
substrate	substrate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
and	and	CC
the	the	ATI
directions	directions	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axes	axes	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plates	plates	NNS
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
with	with	IN
a	a	AT
twist	twist	NN
angle	angle	NN
#	FO
phis	phis	NP
#	FO
=	=	FO
200	200	CD
°		FO
and	and	CC
n·d	nd	NP
=	=	FO
0.7	0.7	CD
according_to	according_to	IN
a	a	AT
further	further	JJR
embodiment	embodiment	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
16	16	CD
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
directions	directions	NNS
of	of	IN
the	the	ATI
substrate	substrate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
and	and	CC
the	the	ATI
directions	directions	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axes	axes	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plates	plates	NNS
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
with	with	IN
a	a	AT
twist	twist	NN
angle	angle	NN
#	FO
phis	phis	NP
#	FO
=	=	FO
200	200	CD
°		FO
and	and	CC
n·d	nd	NP
=	=	FO
0.9	0.9	CD
according_to	according_to	IN
a	a	AT
still	still	RB
further	further	JJR
embodiment	embodiment	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
17	17	CD
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
directions	directions	NNS
of	of	IN
the	the	ATI
substrate	substrate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
and	and	CC
the	the	ATI
directions	directions	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axes	axes	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plates	plates	NNS
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
with	with	IN
a	a	AT
twist	twist	NN
angle	angle	NN
#	FO
phis	phis	NP
#	FO
=	=	FO
240	240	CD
°		FO
and	and	CC
n·d	nd	NP
=	=	FO
0.6	0.6	CD
according_to	according_to	IN
a	a	AT
still	still	RB
another	another	DT
embodiment	embodiment	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
18	18	CD
is	is	BEZ
a	a	AT
plan	plan	NN
view	view	NN
illustrating	illustrating	VBG
the	the	ATI
aligning	aligning	JJing
treatment	treatment	NN
directions	directions	NNS
of	of	IN
the	the	ATI
substrate	substrate	NN
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
and	and	CC
the	the	ATI
directions	directions	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
axes	axes	NNS
of	of	IN
the	the	ATI
polarizing	polarizing	JJing
plates	plates	NNS
on	on	IN
the	the	ATI
incident	incident	NN
light	light	NN
side	side	NN
and	and	CC
outgoing	outgoing	JJing
light	light	NN
side	side	NN
,	,	,
with	with	IN
a	a	AT
twist	twist	NN
angle	angle	NN
#	FO
phis	phis	NP
#	FO
=	=	FO
240	240	CD
°		FO
and	and	CC
n·d	nd	NP
=	=	FO
0.8	0.8	CD
according_to	according_to	IN
a	a	AT
still	still	RB
different	different	JJ
embodiment	embodiment	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
19	19	CD
is	is	BEZ
a	a	AT
block	block	NN
diagram	diagram	NN
schematically	schematically	RB
illustrating	illustrating	VBG
the	the	ATI
arrangement	arrangement	NN
of	of	IN
a	a	AT
driver	driver	NN
for	for	IN
driving	driving	VBG
a	a	AT
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
embodying	embodying	VBG
the	the	ATI
present	present	JJ
invention	invention	NN
;	;	;
Fig.	fig.	NN
20A	20a	NP
is	is	BEZ
a	a	AT
voltage	voltage	NN
waveform	waveform	NN
diagram	diagram	NN
illustrating	illustrating	VBG
a	a	AT
voltage	voltage	NN
at	at	IN
a	a	AT
selected	selected	JJed
element	element	NN
applied	applied	VBN
between	between	IN
signal	signal	NN
electrodes	electrodes	NNS
and	and	CC
scanning	scanning	JJing
electrodes	electrodes	NNS
facing	facing	VBG
each_other	each_other	PPLS
via	via	IN
a	a	AT
liquid	liquid	JJ
crystal	crystal	NN
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
20B	20b	NP
is	is	BEZ
a	a	AT
voltage	voltage	NN
waveform	waveform	NN
diagram	diagram	NN
illustrating	illustrating	VBG
a	a	AT
voltage	voltage	NN
at	at	IN
a	a	AT
half	half	NN
-	-	DA
selected	selected	JJed
element	element	NN
applied	applied	VBN
between	between	IN
the	the	ATI
signal	signal	NN
electrodes	electrodes	NNS
and	and	CC
scanning	scanning	JJing
electrodes	electrodes	NNS
facing	facing	VBG
each_other	each_other	PPLS
via	via	IN
the	the	ATI
liquid	liquid	JJ
crystal	crystal	NN
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
20C	20c	NP
is	is	BEZ
a	a	AT
voltage	voltage	NN
waveform	waveform	NN
diagram	diagram	NN
illustrating	illustrating	VBG
a	a	AT
voltage	voltage	NN
at	at	IN
an	an	AT
unselected	unselected	JJed
element	element	NN
applied	applied	VBN
between	between	IN
the	the	ATI
signal	signal	NN
electrodes	electrodes	NNS
and	and	CC
scanning	scanning	JJing
electrodes	electrodes	NNS
facing	facing	VBG
each_other	each_other	PPLS
via	via	IN
the	the	ATI
liquid	liquid	JJ
crystal	crystal	NN
in	in	IN
the	the	ATI
present	present	JJ
liquid	liquid	NN
crystal	crystal	NN
device	device	NN
;	;	;
Fig.	fig.	NN
21A	21a	NP
is	is	BEZ
a	a	AT
waveform	waveform	NN
diagram	diagram	NN
of	of	IN
an	an	AT
applied	applied	JJed
voltage	voltage	NN
in	in	RP
ON	on	IN
state	state	NN
where	where	WRB
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
is	is	BEZ
driven	driven	VBN
by	by	IN
a	a	AT
drive	drive	NN
signal	signal	NN
having	having	HVG
a	a	AT
frame	frame	NN
frequency	frequency	NN
of	of	IN
60	60	CD
Hz	hz	NNU
;	;	;
Fig.	fig.	NN
21B	21b	NP
is	is	BEZ
a	a	AT
transmittivity	transmittivity	NN
characteristic	characteristic	NN
diagram	diagram	NN
illustrating	illustrating	VBG
a	a	AT
change	change	NN
in	in	IN
light	light	JJ
transmittivity	transmittivity	NN
when	when	WRB
the	the	ATI
voltages	voltages	NNS
having	having	HVG
the	the	ATI
waveform	waveform	NN
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
21A	21a	NP
is	is	BEZ
applied	applied	VBN
to	to	TO
a	a	AT
liquid	liquid	JJ
crystal	crystal	NN
;	;	;
Fig.	fig.	NN
22A	22a	NP
is	is	BEZ
a	a	AT
waveform	waveform	NN
diagram	diagram	NN
of	of	IN
an	an	AT
applied	applied	JJed
voltage	voltage	NN
in	in	RP
ON	on	IN
state	state	NN
where	where	WRB
the	the	ATI
present	present	JJ
liquid	liquid	JJ
crystal	crystal	NN
device	device	NN
is	is	BEZ
driven	driven	VBN
by	by	IN
a	a	AT
drive	drive	NN
signal	signal	NN
having	having	HVG
a	a	AT
frame	frame	NN
frequency	frequency	NN
of	of	IN
120	120	CD
Hz	hz	NNU
;	;	;
and	and	CC
Fig.	fig.	NN
22B	22b	NP
is	is	BEZ
a	a	AT
transmittivity	transmittivity	NN
characteristic	characteristic	NN
diagram	diagram	NN
illustrating	illustrating	VBG
a	a	AT
change	change	NN
in	in	IN
light	light	JJ
transmittivity	transmittivity	NN
when	when	WRB
the	the	ATI
voltage	voltage	NN
having	having	HVG
the	the	ATI
waveform	waveform	NN
shown	shown	VBN
in	in	IN
Fig.	fig.	NN
22A	22a	NP
is	is	BEZ
applied	applied	VBN
to	to	TO
a	a	AT
liquid	liquid	JJ
crystal	crystal	NN
.	.	.

#SENTENCENUM	5102
#SRCFILE	-
In	in	IN
addition	addition	NN
,	,	,
the	the	ATI
noise	noise	NN
filter	filter	NN
9	9	CD
constitutes	constitutes	VBZ
noise	noise	NN
filter	filter	NN
means	means	NNS
whose	whose	WP
frequency	frequency	NN
characteristic	characteristic	NN
is	is	BEZ
selectively	selectively	RB
switched	switched	VBN
per	per	IN
segmental	segmental	JJ
period	period	NN
correspondingly	correspondingly	RB
to	to	TO
the	the	ATI
frequency	frequency	NN
characteristic	characteristic	NN
of	of	IN
the	the	ATI
input	input	NN
digital	digital	JJ
signal	signal	NN
in_accordance_with	in_accordance_with	IN
the	the	ATI
result	result	NN
of	of	IN
detection	detection	NN
by	by	IN
the	the	ATI
spectrum	spectrum	NN
detector	detector	NN
means	means	NNS
and	and	CC
feeding	feeding	VBG
back	back	RP
to	to	TO
the	the	ATI
re-quantizer	re-quantizer	NN
means	means	NNS
the	the	ATI
re-quantization	re-quantization	NN
error	error	NN
signal	signal	NN
S	s	NP
Z2	z2	NP
generated	generated	VBN
during	during	IN
the	the	ATI
re-quantization	re-quantization	NN
.	.	.

#SENTENCENUM	5114
#SRCFILE	-
For	for	IN
the	the	ATI
purposes	purposes	NNS
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
the	the	ATI
donor	donor	NN
number	number	NN
is	is	BEZ
defined	defined	VBN
as	as	IN
the	the	ATI
molar	molar	JJ
enthalpy	enthalpy	NN
value	value	NN
for	for	IN
the	the	ATI
reaction	reaction	NN
of	of	IN
the	the	ATI
electron	electron	NN
donor	donor	NN
with	with	IN
SbCl#sub5	sbcl#sub5	NP
#	FO
as	as	IN
a	a	AT
reference	reference	NN
acceptor	acceptor	NN
in	in	IN
a	a	AT
10#supmin#³M	10#supmin#m	NP
solution	solution	NN
of	of	IN
dichloroethane	dichloroethane	NN
and	and	CC
is	is	BEZ
a	a	AT
measure	measure	NN
of	of	IN
the	the	ATI
tendency	tendency	NN
of	of	IN
the	the	ATI
electron	electron	NN
donor	donor	NN
to	to	TO
share	share	VB
its	its	PP$
electrons	electrons	NNS
with	with	IN
the	the	ATI
acceptor	acceptor	NN
.	.	.

#SENTENCENUM	5120
#SRCFILE	-
It	it	PP3
is	is	BEZ
preferred	preferred	VBN
that	that	CS
the	the	ATI
mole	mole	NN
amount	amount	NN
of	of	IN
electron	electron	NN
donor	donor	NN
used	used	VBN
is	is	BEZ
from	from	IN
about	about	IN
2	2	CD
x	x	CD
10#supmin	10#supmin	NP
#	FO
¹		FO
to	to	TO
about	about	IN
3	3	CD
moles	moles	NNS
per	per	IN
mole	mole	NN
of	of	IN
peroxy	peroxy	NN
compound	compound	NN
.	.	.

#SENTENCENUM	5139
#SRCFILE	-
The	the	ATI
printing	printing	NN
plate	plate	NN
4	4	CD
may	may	NR
for	for	IN
example	example	NN
comprise	comprise	VB
a	a	AT
substrate	substrate	NN
4a	4a	NP
comprising	comprising	VBG
an	an	AT
electroconductive	electroconductive	JJ
material	material	NN
such_as	such_as	IN
metal	metal	NN
,	,	,
and	and	CC
a	a	AT
desired	desired	JJed
pattern	pattern	NN
4b	4b	NP
disposed	disposed	VBN
thereon	thereon	RB
comprising	comprising	VBG
an	an	AT
insulating	insulating	JJing
material	material	NN
,	,	,
as	as	CS
shown	shown	VBN
in	in	IN
Figure	figure	NN
5	5	CD
.	.	.

#SENTENCENUM	5156
#SRCFILE	-
The	the	ATI
routine	routine	NN
may	may	MD
be	be	BE
initiated	initiated	VBN
by	by	IN
a	a	AT
system	system	NN
such_as	such_as	IN
that	that	DT
disclosed	disclosed	VBN
in	in	IN
the	the	ATI
aforementioned	aforementioned	JJ
US-A-4	us-a-4	NP
,	,	,
285,050	285,050	CD
for	for	IN
Electronic	electronic	JJ
Postage	postage	NN
Meter	meter	NN
Operating	operating	VBG
Voltage	voltage	NN
Variation	variation	NN
Sensing	sensing	NN
System	system	NN
.	.	.

#SENTENCENUM	5159
#SRCFILE	-
Therefore	therefore	RB
,	,	,
in	in	IN
FIG.	fig.	NN
3	3	CD
,	,	,
the	the	ATI
delay	delay	NN
function	function	NN
which	which	WP
was	was	BEDZ
implemented	implemented	VBN
by	by	IN
delay	delay	NN
circuit	circuit	NN
24	24	CD
of	of	IN
FIG.	fig.	NN
2	2	CD
is	is	BEZ
accomplished	accomplished	VBN
by	by	IN
delay	delay	NN
circuits	circuits	NNS
33	33	CD
and	and	CC
36	36	CD
and	and	CC
by	by	IN
coupling	coupling	VBG
the	the	ATI
error	error	NN
term	term	NN
e(K-1)	e(k-1)	NP
to	to	TO
multiplier	multiplier	NN
34	34	CD
.	.	.

#SENTENCENUM	5165
#SRCFILE	-
In_order_to	in_order_to	TO
achieve	achieve	VB
the	the	ATI
above	above	JJ
object	object	NN
,	,	,
the	the	ATI
data	data	NN
storage	storage	NN
apparatus	apparatus	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
comprises	comprises	VBZ
:	:	:
a	a	AT
first	first	OD
lever	lever	NN
body	body	NN
having	having	HVG
a	a	AT
piezoelectric	piezoelectric	JJ
driving	driving	NN
section	section	NN
,	,	,
a	a	AT
second	second	OD
lever	lever	NN
body	body	NN
having	having	HVG
a	a	AT
piezoelectric	piezoelectric	JJ
driving	driving	NN
section	section	NN
driven	driven	VBN
in	in	IN
a	a	AT
direction	direction	NN
perpendicular	perpendicular	JJ
to	to	TO
a	a	AT
drive	drive	NN
direction	direction	NN
of	of	IN
the	the	ATI
first	first	OD
lever	lever	NN
body	body	NN
;	;	;
a	a	AT
recording	recording	JJing
medium	medium	NN
,	,	,
formed	formed	VBN
on	on	IN
a	a	AT
portion	portion	NN
of	of	IN
the	the	ATI
second	second	OD
lever	lever	NN
body	body	NN
,	,	,
for	for	IN
recording	recording	VBG
desired	desired	JJed
data	data	NNS
;	;	;
detection	detection	NN
means	means	NNS
,	,	,
disposed	disposed	VBN
on	on	IN
a	a	AT
portion	portion	NN
of	of	IN
the	the	ATI
first	first	OD
lever	lever	NN
body	body	NN
to	to	TO
oppose	oppose	VB
the	the	ATI
recording	recording	JJing
medium	medium	NN
at	at	IN
a	a	AT
predetermined	predetermined	JJed
interval	interval	NN
,	,	,
for	for	IN
detecting	detecting	VBG
a	a	AT
change	change	NN
in	in	IN
state	state	NN
at	at	IN
a	a	AT
predetermined	predetermined	JJed
position	position	NN
on	on	IN
the	the	ATI
recording	recording	JJing
medium	medium	NN
as	as	IN
one	one	PN
of	of	IN
a	a	AT
change	change	NN
in	in	IN
tunnel	tunnel	NN
current	current	NN
and	and	CC
a	a	AT
change	change	NN
in	in	IN
three-dimensional	three-dimensional	JJ
pattern	pattern	NN
;	;	;
and	and	CC
voltage	voltage	NN
applying	applying	JJing
means	means	NNS
for	for	IN
alternately	alternately	RB
applying	applying	VBG
predetermined	predetermined	JJed
voltages	voltages	NNS
to	to	TO
the	the	ATI
piezoelectric	piezoelectric	JJ
driving	driving	NN
sections	sections	NNS
of	of	IN
the	the	ATI
first	first	OD
and	and	CC
second	second	OD
lever	lever	NN
bodies	bodies	NNS
to	to	TO
separately	separately	RB
drive	drive	VB
the	the	ATI
detection	detection	NN
means	means	NNS
in	in	IN
different	different	JJ
directions	directions	NNS
,	,	,
thereby	thereby	RB
three-dimensionally	three-dimensionally	RB
scanning	scanning	VBG
the	the	ATI
recording	recording	JJing
medium	medium	NN
.	.	.

#SENTENCENUM	5190
#SRCFILE	-
The	the	ATI
film	film	NN
thus	thus	RB
obtained	obtained	VBN
was	was	BEDZ
allowed	allowed	VBN
to	to	TO
stand	stand	VB
in	in	IN
a	a	AT
drying	drying	JJing
oven	oven	NN
at	at	IN
a	a	AT
temperature	temperature	NN
of	of	IN
90	90	CD
°C	c	NNU
for	for	IN
100	100	CD
hours	hours	NNS
,	,	,
and	and	CC
as	as	IN
a	a	AT
result	result	NN
it	it	PP3
discolored	discolored	VBD
to	to	TO
brown	brown	NN
and	and	CC
thus	thus	RB
was	was	BEDZ
of	of	IN
inferior	inferior	JJ
heat	heat	NN
resistance	resistance	NN
and	and	CC
durability	durability	NN
.	.	.

#SENTENCENUM	5196
#SRCFILE	-
The	the	ATI
following	following	JJing
Table	table	NN
II	ii	CD
is	is	BEZ
a	a	AT
further	further	JJR
comparison	comparison	NN
of	of	IN
the	the	ATI
electromigration	electromigration	NN
characteristics	characteristics	NNS
of	of	IN
sputtered	sputtered	JJed
Al-0.5%Cu	al-0.5%cu	NN
metallurgy	metallurgy	NN
after	after	IN
annealing	annealing	VBG
with	with	IN
intermetallic	intermetallic	JJ
formation	formation	NN
as	as	CS
compared	compared	VBN
to	to	TO
various	various	JJ
other	other	DT
interconnect	interconnect	NN
metallurgies	metallurgies	NNS
.	.	.

#SENTENCENUM	5225
#SRCFILE	-
These	these	DTS
locations	locations	NNS
can	can	MD
be	be	BE
readily	readily	RB
matched	matched	VBN
to	to	TO
specific	specific	JJ
fragment	fragment	NN
sizes	sizes	NNS
by	by	IN
introduction	introduction	NN
into	into	IN
the	the	ATI
separation	separation	NN
technique	technique	NN
of	of	IN
a	a	AT
marker	marker	NN
such_as	such_as	IN
EcoR	ecor	NP
I	i	CD
digested	digested	JJed
bacterio-phage	bacterio-phage	NN
DNA	dna	NN
.	.	.

#SENTENCENUM	5247
#SRCFILE	-
The	the	ATI
predictive	predictive	JJ
filter	filter	NN
3	3	CD
is	is	BEZ
so	so	RB
formed	formed	VBN
that	that	CS
the	the	ATI
frequency	frequency	NN
characteristic	characteristic	NN
thereof	thereof	RB
is	is	BEZ
selectively	selectively	RB
switched	switched	VBN
in_accordance_with	in_accordance_with	IN
a	a	AT
detection	detection	NN
output	output	NN
signal	signal	NN
Sp	sp	NP
obtained	obtained	VBN
from	from	IN
the	the	ATI
maximum	maximum	JJ
detector	detector	NN
8	8	CD
,	,	,
whereby	whereby	RB
the	the	ATI
frequency	frequency	NN
characteristic	characteristic	NN
H(z)	h(z)	NP
of	of	IN
the	the	ATI
residual	residual	JJ
signal	signal	NN
S	s	NP
Z1	z1	NP
to	to	TO
the	the	ATI
input	input	NN
signal	signal	NN
S	s	NP
I	i	NP
is	is	BEZ
corrected	corrected	VBN
as	as	CS
expressed	expressed	VBN
by	by	IN
the	the	ATI
following	following	JJing
equations	equations	NNS
:	:	:
The	the	ATI
preferred	preferred	JJed
embodiment	embodiment	NN
of	of	IN
the	the	ATI
present	present	JJ
invention	invention	NN
also	also	RB
includes	includes	VBZ
an	an	AT
apparatus	apparatus	NN
for	for	IN
slitting	slitting	VBG
the	the	ATI
spiral	spiral	JJ
pipe	pipe	NN
made	made	VBN
with	with	IN
the	the	ATI
pipe	pipe	NN
forming	forming	VBG
apparatus	apparatus	NN
10	10	CD
.	.	.

#SENTENCENUM	5324
#SRCFILE	-
The	the	ATI
radiolabeled	radiolabeled	JJ
polyspecific	polyspecific	JJ
anti-leukocyte	anti-leukocyte	NN
antibody	antibody	NN
composite	composite	NN
is	is	BEZ
conveniently	conveniently	RB
provided	provided	VBN
as	as	IN
an	an	AT
injectable	injectable	JJ
preparation	preparation	NN
for	for	IN
mammalian	mammalian	JJ
use	use	NN
,	,	,
preferably	preferably	RB
a	a	AT
sterile	sterile	JJ
injectable	injectable	JJ
preparation	preparation	NN
for	for	IN
human	human	JJ
use	use	NN
,	,	,
for	for	IN
targeting	targeting	VBG
a	a	AT
scintigraphic	scintigraphic	JJ
imaging	imaging	JJing
agent	agent	NN
to	to	TO
an	an	AT
infectious	infectious	JJ
or	or	CC
inflammatory	inflammatory	JJ
lesion	lesion	NN
containing	containing	VBG
leukocytes	leukocytes	NNS
,	,	,
preferably	preferably	RB
comprising	comprising	VBG
:	:	:
a	a	AT
sterile	sterile	JJ
injectable	injectable	JJ
solution	solution	NN
containing	containing	VBG
an	an	AT
effective	effective	JJ
amount	amount	NN
of	of	IN
the	the	ATI
radiolabeled	radiolabeled	JJ
composite	composite	NN
in	in	IN
a	a	AT
pharmaceutically	pharmaceutically	RB
acceptible	acceptible	JJ
sterile	sterile	JJ
injection	injection	NN
vehicle	vehicle	NN
,	,	,
preferably	preferably	RB
phosphate-buffered	phosphate-buffered	JJed
saline	saline	NN
at	at	IN
physiological	physiological	JJ
pH	ph	NN
and	and	CC
concentration	concentration	NN
.	.	.

#SENTENCENUM	5355
#SRCFILE	-
Although	although	CS
the	the	ATI
exhaust	exhaust	JJ
gas	gas	NN
temperature	temperature	NN
is	is	BEZ
at	at	IN
a	a	AT
minimum	minimum	NN
at	at	IN
the	the	ATI
exhaust	exhaust	NN
output	output	NN
end	end	NN
of	of	IN
exhaust	exhaust	JJ
gas	gas	NN
output	output	NN
section	section	NN
16	16	CD
,	,	,
illustratively	illustratively	RB
266	266	CD
.degree.	.degree.	NNU
F.	f.	NNU
,	,	,
it	it	PP3
is	is	BEZ
above	above	IN
the	the	ATI
exhaust	exhaust	JJ
gas	gas	NN
dew	dew	NN
point	point	NN
.	.	.

#SENTENCENUM	5393
#SRCFILE	-
A	a	AT
first	first	OD
way	way	NN
of	of	IN
conducting	conducting	VBG
the	the	ATI
test	test	NN
consists	consists	VBZ
of	of	IN
measuring	measuring	NN
,	,	,
versus	versus	IN
time	time	NN
,	,	,
the	the	ATI
accumulated	accumulated	JJed
volume	volume	NN
of	of	IN
filtrate	filtrate	NN
of	of	IN
the	the	ATI
polysaccharide	polysaccharide	NN
solution	solution	NN
passing	passing	VBG
through	through	IN
a	a	AT
calibrated	calibrated	JJed
filter	filter	NN
of	of	IN
47	47	CD
mm	mm	NNU
diameter	diameter	NN
or	or	CC
still	still	RB
of	of	IN
142	142	CD
mm	mm	NNU
diameter	diameter	NN
and	and	CC
whose	whose	WDT
pore	pore	NN
size	size	NN
ranges	ranges	VBZ
from	from	IN
0.45	0.45	CD
to	to	TO
5.0	5.0	CD
.mu.m	.mu.m	NP
under	under	IN
a	a	AT
constant	constant	JJ
manometric	manometric	JJ
pressure	pressure	NN
from	from	IN
10	10	CD
kPa	kpa	NNU
to	to	TO
300	300	CD
kPa	kpa	NNU
,	,	,
thus	thus	RB
simulating	simulating	VBG
both	both	ABX
the	the	ATI
pore	pore	NN
size	size	NN
of	of	IN
the	the	ATI
formation	formation	NN
around	around	IN
the	the	ATI
injection	injection	NN
well	well	NN
and	and	CC
the	the	ATI
high	high	JJ
pressure	pressure	NN
drops	drops	NNS
encountered	encountered	VBN
therein	therein	RB
.	.	.

#SENTENCENUM	5410
#SRCFILE	-
Furthermore	furthermore	RB
,	,	,
the	the	ATI
buried	buried	JJed
base	base	JJ
grid	grid	NN
contact	contact	NN
142	142	CD
can	can	MD
further	further	RB
include	include	VB
a	a	AT
buried	buried	JJed
metal	metal	JJ
region	region	NN
,	,	,
similar	similar	JJ
to	to	TO
that	that	WP
in	in	IN
FIG.	fig.	NN
11	11	CD
,	,	,
FIG.	fig.	NN
21	21	CD
or	or	CC
as	as	CS
shown	shown	VBN
in	in	IN
related	related	JJed
application	application	NN
UNI-049XX	uni-049xx	NN
,	,	,
to	to	TO
further	further	RBR
reduce	reduce	VB
the	the	ATI
resistance	resistance	NN
of	of	IN
base	base	JJ
region	region	NN
142	142	CD
.	.	.

#SENTENCENUM	5438
#SRCFILE	-
A	a	AT
microwave	microwave	NN
dielectric	dielectric	JJ
composition	composition	NN
,	,	,
comprising	comprising	VBG
a	a	AT
basic	basic	JJ
composition	composition	NN
,	,	,
represented	represented	VBN
by	by	IN
the	the	ATI
following	following	JJing
formula	formula	NN
:	:	:
(Pb(1-x)Ca(x))(Zr(1-y)Sn(y))O(3)	(pb(1-x)ca(x))(zr(1-y)sn(y))o(3)	NP
wherein	wherein	WRB
x	x	NP
and	and	CC
y	y	NP
are	are	BER
molar	molar	JJ
ratios	ratios	NNS
in	in	IN
the	the	ATI
relation	relation	NN
of	of	IN
0.15<x<0.40	0.15<x<0.40	NP
and	and	CC
0.15<y<0.50	0.15<y<0.50	NP
,	,	,
and	and	CC
a	a	AT
sintering	sintering	JJing
aid	aid	NN
represented	represented	VBN
by	by	IN
the	the	ATI
following	following	JJing
formula	formula	NN
:	:	:
a	a	AT
ZnO+b	zno+b	NP
Sb.sub.2	sb.sub.2	NP
O.sub.3	o.sub.3	NP
wherein	wherein	WRB
a	a	NP
and	and	CC
b	b	NP
are	are	BER
percentages	percentages	NNS
relative	relative	JJ
to	to	IN
the	the	ATI
total	total	JJ
weight	weight	NN
of	of	IN
the	the	ATI
basic	basic	JJ
composition	composition	NN
,	,	,
in	in	IN
the	the	ATI
relation	relation	NN
of	of	IN
0<a+b<0.05	0<a+b<0.05	NP
weight	weight	NN
%	%	NNU
.	.	.

#SENTENCENUM	5445
#SRCFILE	-
A	a	AT
monoclonal	monoclonal	JJ
antibody	antibody	NN
or	or	CC
antigen	antigen	NN
binding	binding	JJing
fragment	fragment	NN
thereof	thereof	RB
which	which	WP
recognizes	recognizes	VBZ
light	light	JJ
meromyosin	meromyosin	NN
fragments	fragments	NNS
of	of	IN
.alpha.-	.alpha.-	JJ
and	and	CC
.beta.-type	.beta.-type	JJ
human	human	JJ
cardiac	cardiac	JJ
myosin	myosin	JJ
heavy	heavy	JJ
chains	chains	NNS
that	that	WP
remain	remain	VB
in	in	IN
situ	situ	NN
after	after	CS
myocardial	myocardial	JJ
cell	cell	NN
death	death	NN
is	is	BEZ
described	described	VBN
.	.	.

#SENTENCENUM	5639
#SRCFILE	-
RU486-mediated	ru486-mediated	JJed
luteolysis	luteolysis	NN
appears	appears	VBZ
to	to	TO
be	be	BE
secondary	secondary	JJ
to	to	TO
changes	changes	NNS
in	in	IN
gonadotrophin	gonadotrophin	NN
secretion	secretion	NN
and	and	CC
thus	thus	RB
the	the	ATI
effects	effects	NNS
are	are	BER
similar	similar	JJ
to	to	TO
those	those	DTS
following	following	VBG
exogenous	exogenous	JJ
progesterone	progesterone	NN
administration	administration	NN
.	.	.

#SENTENCENUM	5640
#SRCFILE	-
Reaction	reaction	NN
between	between	IN
lactose	lactose	NN
lactone	lactone	NN
and	and	CC
the	the	ATI
functional	functional	JJ
group	group	NN
of	of	IN
IFN	ifn	NP
efficiently	efficiently	RB
gives	gives	VBZ
sugar-modified	sugar-modified	JJed
IFN	ifn	NP
having	having	HVG
a	a	AT
galactose	galactose	NN
residue	residue	NN
in	in	IN
the	the	ATI
intramolecular	intramolecular	JJ
and/or	and/or	CC
terminal	terminal	JJ
functional	functional	JJ
group(s)	group(s)	NNS
of	of	IN
IFN	ifn	NP
molecule	molecule	NN
.	.	.

#SENTENCENUM	5681
#SRCFILE	-
Referring	referring	VBG
to	to	TO
FIG.	fig.	NN
7	7	CD
showing	showing	VBG
the	the	ATI
refrigerator	refrigerator	NN
control	control	JJ
apparatus	apparatus	NN
according_to	according_to	IN
still	still	RB
another	another	DT
embodiment	embodiment	NN
of	of	IN
the	the	ATI
invention	invention	NN
,	,	,
a	a	AT
control	control	JJ
circuit	circuit	NN
is	is	BEZ
illustrated	illustrated	VBN
which	which	WP
is	is	BEZ
a	a	AT
combination	combination	NN
of	of	IN
the	the	ATI
preceding	preceding	JJ
couple	couple	NN
of	of	IN
embodiments	embodiments	NNS
and	and	CC
capable	capable	JJ
of	of	IN
overload	overload	NN
control	control	NN
and	and	CC
defrosting	defrosting	NN
control	control	NN
at_the_same_time	at_the_same_time	RB
.	.	.

#SENTENCENUM	5737
#SRCFILE	-
As	as	CS
seen	seen	VBN
from	from	IN
FIG.	fig.	NN
10	10	CD
,	,	,
the	the	ATI
regions	regions	NNS
of	of	IN
the	the	ATI
constant	constant	JJ
current-source	current-source	NN
FETs	fets	NNS
Q4'	q4'	NP
and	and	CC
Q5'	q5'	NP
of	of	IN
the	the	ATI
input	input	NN
stage	stage	NN
are	are	BER
located	located	VBN
near	near	IN
the	the	ATI
region	region	NN
of	of	IN
the	the	ATI
constant	constant	JJ
current-source	current-source	NN
FET	fet	NN
Q3'	q3'	NP
of	of	IN
the	the	ATI
output	output	NN
stage	stage	NN
,	,	,
and	and	CC
symmetrically	symmetrically	RB
with	with	IN
respect	respect	NN
the	the	ATI
center	center	NN
thereof	thereof	RB
.	.	.

