#!/usr/bin/env ruby
# -*- coding: utf-8; -*-

# # #
#
#

require 'optparse'

tagset = {
  'SI' => 'initial character, space on the left',
  'SM' => 'middle character, no spaces around',
  'SL' => 'last character, space on the ritht',
  'SW' => 'character is a word, spaces on both sides'
}

empty_line_label = '#!#EMPTYLINE'

OptionParser.new do |opts|
  opts.banner = "
  Given the data outputted by CRF (in vertical form), restore spaces
based on the following meaning of the tags:
#{tagset.map {|a| "    " + a.join(' -- ')}.join("\n")}
Note: for the script to work correctly the file must end with an empty line
USAGE: #{File.basename($0)} [OPTIONS] input_file(s)
OPTIONS:
"

  opts.on('-h', '--help', 'display this message and exit') do
    puts opts
    exit 0
  end

  @restore_empty_lines = true
  opts.on('--[no-]restore-empty-lines',
          "replace #{empty_line_label} with an empty line",
          'The default is to automatically recognize the label') do |val|
    @restore_empty_lines = val
  end

  opts.separator " "
end.parse!

Encoding::default_external = 'UTF-8'

def restore_spaces(ch, tag)
# puts "char/tag: #{char}/#{tag}"
  case tag
  when 'SW'
    " #{ch} "
  when 'SI'
    " #{ch}"
  when 'SL'
    "#{ch} "
  else
    ch
  end
end

def join_chars lines

  chars = lines.map do |line|
    char, *tmp, tag = line.split(/\t/)
    restore_spaces(char, tag)
  end

  line = chars.join('').squeeze(' ').strip

  return line
end

lines = []
while line = gets
  line.chomp!

  if line == empty_line_label && @restore_empty_lines
    puts ""

  elsif line.empty?
    puts join_chars(lines)
    lines.clear

  else
    lines << line
  end

end

