#!/usr/bin/env ruby

# # #
# A number is even if its predecessor is odd.
# A number is odd if is not even.
# The number 0 is even by definition.
#
# works for nonnegative integers only
#


def odd? n
  !even?(n)
end

def even? n
#  if n == 0
#    true
#  else
#    odd?(n-1)
#  end
  n == 0 || odd?(n-1)
end

puts even?(0)  == true
puts even?(2)  == true
puts even?(22) == true

puts even?(1)  == false
puts even?(21) == false

puts even?(999) == false
puts odd?(999)  == true
