#!/usr/bin/env ruby

def sum_digits num
  if num < 10
    num
  else
    # 123 % 10 = 3
    # 123 / 10 = 12
    num % 10 + sum_digits(num / 10)
  end
end

puts 0 == sum_digits(0)
puts 1 == sum_digits(10)
puts 6 == sum_digits(123)
puts 7 == sum_digits(2014)

