#!/usr/bin/env ruby

# # #
# USAGE: find_all_anagrams.rb words.txt
#

def hashcode_of(word)
  word.downcase.split('').sort.join
end

anagrams = {}

while word = gets
  word.chomp!

  if word.length > 1
    hcode = hashcode_of(word)

    anagrams[hcode] ||= []
    anagrams[hcode] << word
  end

end

c_out = 0
anagrams.values.each do |words|
  if words.length > 1
    puts words.join("\t")
    c_out += 1
  end
end

$stderr.puts "Anagram groups: #{c_out}"

