#!/usr/bin/env ruby

#action, prep = 2, 5 # ESE
action, prep = 2, 6 # GSE

while block = gets("")
  lines = block.split(/\n/)

  counts = Hash.new {|h,k| h[k] = 0}
  lines.each do |line|
    if line =~ /r__VerbPhrase/
      fields = line.split(/\t/, -1)
      unless fields[prep].empty?
        counts[fields[action]] += 1
      end
    end
  end

  if counts.any? {|field, count| count > 1}
    puts "#COUNTS\t"+ counts.inspect
    puts block
  end

end


