#!/usr/bin/ruby

require 'json'

h = {"one" => "uno", "two" => "dos", :three => "tres"}
a = ["hello", h, 42]

puts "a: " + a.inspect

serialized = JSON.dump(a)

puts "JSON data looks like"
puts serialized

# Note, class Symbol was converted to String
puts "Deserialized using JSON.load"
b = JSON.load(serialized)
puts "b: " + b.inspect

puts "Deserialized using JSON.parse"
c = JSON.parse(serialized)
puts "c: " + c.inspect

puts "Restored from the result of inspect using JSON.parse"
puts JSON.parse([12, "hello"].inspect)

